spring:
  application:
    name: eureka-discovery-serviceg

server:
  port: 8761
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka